services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - '3001:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - node-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    networks:
      - node-network

volumes:
  mongo_data:
    driver: local

networks:
  node-network:
    driver: bridge
